version: '3'

services:
    backapp:
        build: backend-app/
        entrypoint: ./.docker/entrypoint.sh
        container_name: nestjs-backapp
        volumes:
            - ./backend-app/:/home/node/app
    
    frontapp:
        build: frontend-app/
        entrypoint: ./.docker/entrypoint.sh
        container_name: nextjs-frontapp
        ports:
            - 3001:3001
        volumes:
            - ./frontend-app/:/home/node/app
        extra_hosts: 
            - 'host.docker.internal:172.17.0.1'